/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.controladores.ControladorFactura;
import ec.edu.ups.controladores.ControladorFacturaDetalle;
import ec.edu.ups.controladores.ControladorProducto;
import ec.edu.ups.modelo.Cliente;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Byron PC
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControladorCliente controladorcliente;
    private ControladorFactura controladorfactura;
    private ControladorFacturaDetalle controladorfacturadet;
    private ControladorProducto controladorproducto;
    private Locale locatizacion;
    private ResourceBundle mensajes;

    /**
     *
     * Creates new form Ventana
     *
     */
    public VentanaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        controladorcliente = new ControladorCliente();
        controladorproducto = new ControladorProducto();
        //System.out.println("Localizacion por defecto: "+ Locale.getDefault().getLanguage());
        locatizacion = new Locale("es", "EC");
        //Locale.setDefault(locatizacion);
        //System.out.println("Localizacion Forzada: "+ Locale.getDefault().getLanguage());
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", Locale.getDefault());
        //System.out.println("Mensajes");
        //System.out.println(mensajes.getString("menu.item.crear"));

    }

    public void cambiaridioma() {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", Locale.getDefault());
        clientemenu.setText(mensajes.getString("menu.cliente"));
        productomenu.setText(mensajes.getString("menu.producto"));
        facturamenu.setText(mensajes.getString("menu.factura"));
        idiomamenu.setText(mensajes.getString("menu.idioma"));
        detalle.setText(mensajes.getString("menu.facturadetalle"));

        btncrearfacturadet.setText(mensajes.getString("menu.item.detalle"));
        btncrear.setText(mensajes.getString("menu.item.crear"));
        btnproductocrear.setText(mensajes.getString("menu.item.crear"));
        btnfacturacrear.setText(mensajes.getString("menu.item.crear"));

        btnleer.setText(mensajes.getString("menu.item.buscar"));
        btnproductoleeer.setText(mensajes.getString("menu.item.buscar"));
        btnfacturaleeer.setText(mensajes.getString("menu.item.buscar"));

        btnactualizar.setText(mensajes.getString("menu.item.modificar"));
        btnproductomodificar.setText(mensajes.getString("menu.item.modificar"));

        btnborrar.setText(mensajes.getString("menu.item.borrar"));
        btnproductoeliminar.setText(mensajes.getString("menu.item.borrar"));
        btnfacturaborrar.setText(mensajes.getString("menu.item.borrar"));

        btnlistar.setText(mensajes.getString("menu.item.listar"));
        btnproductolista.setText(mensajes.getString("menu.item.listar"));

        btnespañol.setText(mensajes.getString("menu.item.español"));
        btningles.setText(mensajes.getString("menu.item.ingles"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        clientemenu = new javax.swing.JMenu();
        btncrear = new javax.swing.JMenuItem();
        btnleer = new javax.swing.JMenuItem();
        btnactualizar = new javax.swing.JMenuItem();
        btnborrar = new javax.swing.JMenuItem();
        btnlistar = new javax.swing.JMenuItem();
        productomenu = new javax.swing.JMenu();
        btnproductocrear = new javax.swing.JMenuItem();
        btnproductoleeer = new javax.swing.JMenuItem();
        btnproductomodificar = new javax.swing.JMenuItem();
        btnproductoeliminar = new javax.swing.JMenuItem();
        btnproductolista = new javax.swing.JMenuItem();
        facturamenu = new javax.swing.JMenu();
        btnfacturacrear = new javax.swing.JMenuItem();
        btnfacturaleeer = new javax.swing.JMenuItem();
        btnfacturaborrar = new javax.swing.JMenuItem();
        detalle = new javax.swing.JMenu();
        btncrearfacturadet = new javax.swing.JMenuItem();
        idiomamenu = new javax.swing.JMenu();
        btnespañol = new javax.swing.JMenuItem();
        btningles = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientemenu.setMnemonic('f');
        clientemenu.setText("Cliente");

        btncrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        btncrear.setMnemonic('o');
        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });
        clientemenu.add(btncrear);

        btnleer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        btnleer.setMnemonic('s');
        btnleer.setText("Buscar");
        btnleer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleerActionPerformed(evt);
            }
        });
        clientemenu.add(btnleer);

        btnactualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        btnactualizar.setMnemonic('a');
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        clientemenu.add(btnactualizar);

        btnborrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        btnborrar.setMnemonic('x');
        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });
        clientemenu.add(btnborrar);

        btnlistar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        btnlistar.setText("Listar");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        clientemenu.add(btnlistar);

        menuBar.add(clientemenu);

        productomenu.setMnemonic('e');
        productomenu.setText("Producto");

        btnproductocrear.setMnemonic('t');
        btnproductocrear.setText("Crear");
        btnproductocrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductocrearActionPerformed(evt);
            }
        });
        productomenu.add(btnproductocrear);

        btnproductoleeer.setMnemonic('y');
        btnproductoleeer.setText("Leer");
        btnproductoleeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductoleeerActionPerformed(evt);
            }
        });
        productomenu.add(btnproductoleeer);

        btnproductomodificar.setMnemonic('p');
        btnproductomodificar.setText("Actualizar");
        btnproductomodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductomodificarActionPerformed(evt);
            }
        });
        productomenu.add(btnproductomodificar);

        btnproductoeliminar.setMnemonic('d');
        btnproductoeliminar.setText("Borrar");
        btnproductoeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductoeliminarActionPerformed(evt);
            }
        });
        productomenu.add(btnproductoeliminar);

        btnproductolista.setText("Listar");
        btnproductolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductolistaActionPerformed(evt);
            }
        });
        productomenu.add(btnproductolista);

        menuBar.add(productomenu);

        facturamenu.setMnemonic('h');
        facturamenu.setText("Factura");

        btnfacturacrear.setMnemonic('c');
        btnfacturacrear.setText("Crear");
        btnfacturacrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturacrearActionPerformed(evt);
            }
        });
        facturamenu.add(btnfacturacrear);

        btnfacturaleeer.setMnemonic('a');
        btnfacturaleeer.setText("Leer");
        btnfacturaleeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturaleeerActionPerformed(evt);
            }
        });
        facturamenu.add(btnfacturaleeer);

        btnfacturaborrar.setText("Borrar");
        btnfacturaborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturaborrarActionPerformed(evt);
            }
        });
        facturamenu.add(btnfacturaborrar);

        menuBar.add(facturamenu);

        detalle.setText("Factura Detalle");

        btncrearfacturadet.setText("Detalle");
        btncrearfacturadet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearfacturadetActionPerformed(evt);
            }
        });
        detalle.add(btncrearfacturadet);

        menuBar.add(detalle);

        idiomamenu.setText("Idioma");

        btnespañol.setText("Español");
        btnespañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnespañolActionPerformed(evt);
            }
        });
        idiomamenu.add(btnespañol);

        btningles.setText("Ingles");
        btningles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninglesActionPerformed(evt);
            }
        });
        idiomamenu.add(btningles);

        menuBar.add(idiomamenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        String x = VentanaBorrarCliente.x;
        try {
            if (x == null) {
                VentanaBorrarCliente borrarclinte = new VentanaBorrarCliente(controladorcliente);

                desktopPane.add(borrarclinte);
                desktopPane.moveToFront(borrarclinte);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
        String x = VentanaListarClientes.x;
        try {
            if (x == null) {
                VentanaListarClientes listarcliente = new VentanaListarClientes(controladorcliente);

                desktopPane.add(listarcliente);
                desktopPane.moveToFront(listarcliente);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        // TODO add your handling code here:
        String x = VentanaCrearCliente.x;
        try {
            if (x == null) {
                VentanaCrearCliente crearcliente = new VentanaCrearCliente(controladorcliente);

                desktopPane.add(crearcliente);
                desktopPane.moveToFront(crearcliente);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btncrearActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        String x = VentanaActualizarCliente.x;
        try {
            if (x == null) {
                VentanaActualizarCliente actualizarcliente = new VentanaActualizarCliente(controladorcliente);

                desktopPane.add(actualizarcliente);
                desktopPane.moveToFront(actualizarcliente);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnleerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleerActionPerformed
        // TODO add your handling code here:
        String x = VentanaBuscarCliente.x;
        try {
            if (x == null) {
                VentanaBuscarCliente buscarcliente = new VentanaBuscarCliente(controladorcliente);

                desktopPane.add(buscarcliente);
                desktopPane.moveToFront(buscarcliente);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnleerActionPerformed

    private void btnespañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnespañolActionPerformed
        // TODO add your handling code here:
        locatizacion = new Locale("es", "EC");
        Locale.setDefault(locatizacion);
        cambiaridioma();
    }//GEN-LAST:event_btnespañolActionPerformed

    private void btninglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninglesActionPerformed
        // TODO add your handling code here:
        locatizacion = new Locale("en", "US");
        Locale.setDefault(locatizacion);
        cambiaridioma();
    }//GEN-LAST:event_btninglesActionPerformed

    private void btnproductocrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductocrearActionPerformed
        // TODO add your handling code here:
        String x = VentanaCrearProducto.x;
        try {
            if (x == null) {
                VentanaCrearProducto crearProducto = new VentanaCrearProducto(controladorproducto);

                desktopPane.add(crearProducto);
                desktopPane.moveToFront(crearProducto);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnproductocrearActionPerformed

    private void btnproductoleeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductoleeerActionPerformed
        // TODO add your handling code here:
        String x = VentanaBuscarProducto.x;
        try {
            if (x == null) {
                VentanaBuscarProducto buscarproducto = new VentanaBuscarProducto(controladorproducto);

                desktopPane.add(buscarproducto);
                desktopPane.moveToFront(buscarproducto);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnproductoleeerActionPerformed

    private void btnproductomodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductomodificarActionPerformed
        // TODO add your handling code here:
        String x = VentanaActualizarProducto.x;
        try {
            if (x == null) {
                VentanaActualizarProducto actualizarproducto = new VentanaActualizarProducto(controladorproducto);

                desktopPane.add(actualizarproducto);
                desktopPane.moveToFront(actualizarproducto);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnproductomodificarActionPerformed

    private void btnproductoeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductoeliminarActionPerformed
        // TODO add your handling code here:
        String x = VentanaBorrarProducto.x;
        try {
            if (x == null) {
                VentanaBorrarProducto borrarproducto = new VentanaBorrarProducto(controladorproducto);

                desktopPane.add(borrarproducto);
                desktopPane.moveToFront(borrarproducto);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnproductoeliminarActionPerformed

    private void btnproductolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductolistaActionPerformed
        // TODO add your handling code here:

        String x = VentanaListarProductos.x;
        try {
            if (x == null) {
                VentanaListarProductos listarpro = new VentanaListarProductos(controladorproducto);

                desktopPane.add(listarpro);
                desktopPane.moveToFront(listarpro);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnproductolistaActionPerformed

    private void btnfacturacrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturacrearActionPerformed
        // TODO add your handling code here:

        String x = VentanaCrearFactura.x;
        try {
            if (x == null) {
                VentanaCrearFactura crearfactura = new VentanaCrearFactura(controladorcliente, controladorfactura, controladorproducto, controladorfacturadet);

                desktopPane.add(crearfactura);
                desktopPane.moveToFront(crearfactura);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnfacturacrearActionPerformed

    private void btncrearfacturadetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearfacturadetActionPerformed
        // TODO add your handling code here:

        String x = VentanaCrearFacturaDetalle.x;
        try {
            if (x == null) {
                VentanaCrearFacturaDetalle facturadetalle = new VentanaCrearFacturaDetalle(controladorfacturadet, controladorproducto);
                desktopPane.add(facturadetalle);
                desktopPane.moveToFront(facturadetalle);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btncrearfacturadetActionPerformed

    private void btnfacturaborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturaborrarActionPerformed
        // TODO add your handling code here:

        String x = VentanaBorrarFactura.x;
        try {
            if (x == null) {
                VentanaBorrarFactura borrarfactura = new VentanaBorrarFactura(controladorproducto, controladorcliente, controladorfactura);

                desktopPane.add(borrarfactura);
                desktopPane.moveToFront(borrarfactura);

            } else {
                JOptionPane.showMessageDialog(rootPane, "La ventana esta en ejecucion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnfacturaborrarActionPerformed

    private void btnfacturaleeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturaleeerActionPerformed
        // TODO add your handling code here:
        String x = VentanaLeerFactura.x;
        try {
            if (x == null) {
                VentanaLeerFactura leerfactura = new VentanaLeerFactura(controladorcliente);
                desktopPane.add(leerfactura);
                desktopPane.moveToFront(leerfactura);
            }else{
                JOptionPane.showMessageDialog(null, "La ventana esta en ejecucion");
                }
        }catch(Exception e){
                        e.printStackTrace();
                        }
    }//GEN-LAST:event_btnfacturaleeerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnactualizar;
    private javax.swing.JMenuItem btnborrar;
    private javax.swing.JMenuItem btncrear;
    private javax.swing.JMenuItem btncrearfacturadet;
    private javax.swing.JMenuItem btnespañol;
    private javax.swing.JMenuItem btnfacturaborrar;
    private javax.swing.JMenuItem btnfacturacrear;
    private javax.swing.JMenuItem btnfacturaleeer;
    private javax.swing.JMenuItem btningles;
    private javax.swing.JMenuItem btnleer;
    private javax.swing.JMenuItem btnlistar;
    private javax.swing.JMenuItem btnproductocrear;
    private javax.swing.JMenuItem btnproductoeliminar;
    private javax.swing.JMenuItem btnproductoleeer;
    private javax.swing.JMenuItem btnproductolista;
    private javax.swing.JMenuItem btnproductomodificar;
    private javax.swing.JMenu clientemenu;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu detalle;
    private javax.swing.JMenu facturamenu;
    private javax.swing.JMenu idiomamenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productomenu;
    // End of variables declaration//GEN-END:variables

}
